name: Set up Conda environment
inputs:
  environment-file:
    description: Conda environment file to use.
    default: environment.yml
runs:
  using: composite
  steps:
    - name: Install ${{ inputs.environment-file }}
      uses: mamba-org/setup-micromamba@v2
      with:
        # Pinning to due solver performance regressions
        micromamba-version: '2.1.0'
        environment-file: ${{ inputs.environment-file }}
        environment-name: test
        condarc-file: ci/.condarc
        cache-environment: true
        cache-downloads: true
        cache-downloads-key: "foobar1"
        cache-environment-key: "foobar2"
        log-level: trace
        create-args: --strict-channel-priority

    - name: Uninstall pyarrow
      if: ${{ env.REMOVE_PYARROW == '1' }}
      run: |
        micromamba remove -y pyarrow
      shell: bash -el {0}
