name: Build pandas
description: Rebuilds the C extensions and installs pandas
inputs:
  editable:
    description: Whether to build pandas in editable mode (default true)
    default: true
  werror:
    description: Enable werror flag for build
    default: true
runs:
  using: composite
  steps:

    - name: Environment Detail
      run: |
        micromamba info
        micromamba list
        pip list --pre
      shell: bash -el {0}

    - name: Uninstall existing Pandas installation
      run: |
        if pip show pandas 1>/dev/null; then
          pip uninstall -y pandas
        fi
      shell: bash -el {0}

    - name: Build Pandas
      run: |
        SETUP_ARGS=""
        if [[ ${{ inputs.werror }} == "true" ]]; then
          SETUP_ARGS="--werror"
        fi
        if [[ ${{ inputs.editable }} == "true" ]]; then
          pip install -e . --no-build-isolation -v --no-deps \
            -Csetup-args=$SETUP_ARGS
        else
          pip install . --no-build-isolation -v --no-deps \
            -Csetup-args=$SETUP_ARGS
        fi
      shell: bash -el {0}
