name: Test win_arm64 Wheel builder

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheel for cp312-win_arm64
    runs-on: windows-11-arm
    strategy:
      fail-fast: false
      matrix:
        buildplat:
        - [windows-11-arm, win_arm64]
        python: [["cp312", "3.12"]]

    steps:
      - name: Checkout pandas
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3
        with:
         package-dir: ./  # Build from source checkout
        env:
          CIBW_BUILD: ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}
          CIBW_BUILD_FRONTEND: 'pip'
          CIBW_PLATFORM: 'auto'
          CIBW_BEFORE_BUILD_WINDOWS: |
            echo "Attempting to set up MSVC ARM64 environment..."
            set VCVARS_PATH_ENTERPRISE="C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat"
            set VCVARS_PATH_BUILDTOOLS="C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat"
            set CHOSEN_VCVARS_PATH=

            if exist %VCVARS_PATH_ENTERPRISE% (
              echo "Found VS Enterprise vcvarsall.bat: %VCVARS_PATH_ENTERPRISE%"
              set CHOSEN_VCVARS_PATH=%VCVARS_PATH_ENTERPRISE%
            ) else if exist %VCVARS_PATH_BUILDTOOLS% (
              echo "Found VS Build Tools vcvarsall.bat: %VCVARS_PATH_BUILDTOOLS%"
              set CHOSEN_VCVARS_PATH=%VCVARS_PATH_BUILDTOOLS%
            ) else (
              echo "ERROR: vcvarsall.bat not found at expected locations."
              exit /b 1
            )

            echo "Calling %CHOSEN_VCVARS_PATH% arm64"
            call %CHOSEN_VCVARS_PATH% arm64
            if errorlevel 1 (
              echo "ERROR: vcvarsall.bat execution failed."
              exit /b 1
            )
            echo "MSVC environment setup complete."
            echo "Verifying cl.exe:"
            where cl
            if errorlevel 1 (
              echo "ERROR: cl.exe not found in PATH after vcvarsall.bat."
              exit /b 1
            )
            echo "PATH is: %PATH%"
            echo "INCLUDE is: %INCLUDE%"
            echo "LIB is: %LIB%"
          CIBW_ENVIRONMENT_WINDOWS: 'CC=cl CXX=cl CL=/Brepro _CL_=/Brepro'

      - name: Set up Python for validation
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: wheel-env
          create-args: >-
            python=3.12
            wheel
          cache-downloads: true
          cache-environment: true

      - name: Validate wheel RECORD
        shell: bash -el {0}
        run: for whl in $(ls wheelhouse); do wheel unpack wheelhouse/$whl -d /tmp; done

      # Artifact upload is removed as per requirements
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}
      #     path: ./wheelhouse/*.whl
